{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "check-k8s-deprecated-apis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "check-k8s-deprecated-apis.fullname" . }}
    helm.sh/chart: {{ include "check-k8s-deprecated-apis.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "check-k8s-deprecated-apis.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
