apiVersion: v1
kind: Secret
metadata:
  name: {{ include "check-k8s-deprecated-apis.serviceAccountName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "check-k8s-deprecated-apis.serviceAccountName" . }}
type: kubernetes.io/service-account-token
