{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "check-k8s-deprecated-apis.serviceAccountName" . }}
  labels:
    {{- include "check-k8s-deprecated-apis.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    "helm.sh/hook": "pre-install"
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
